services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line cannot change.
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line cannot change.
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nextcloud-aio
    ports:
      - 0.0.0.0:8080:8080
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 127.0.0.1
      SKIP_DOMAIN_VALIDATION: true
      NEXTCLOUD_DATADIR: /data/nextcloud
      NEXTCLOUD_MOUNT: /data/
      NEXTCLOUD_MAX_TIME: 18000 # Upload time limit (sec).
      NEXTCLOUD_ENABLE_DRI_DEVICE: true # Allow hardware transcoding. only works if `/dev/dri` is present on the host.
      AIO_COMMUNITY_CONTAINERS: "memories"
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    container_name: nextcloud-aio-jellyfin
    volumes:
      - /data/nextcloud/jellyfin-config:/config
      - /data/nextcloud/jellyfin-cache:/cache
      - type: bind
        source: /data/nextcloud
        target: /media
      - type: bind
        source: /usr/share/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    networks:
      - nextcloud-aio
    ports:
      - 8096:8096/tcp # HTTP (no SSL)
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: nextcloud-aio-caddy
    environment:
      - NC_DOMAIN
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - type: volume
        source: caddy_certs
        target: /certs
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
      - type: volume
        source: tailscale_sock
        target: /var/run/tailscale/ # Mount the volume for /var/run/tailscale/tailscale.sock
        read_only: true
    network_mode: service:tailscale
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      - TS_HOSTNAME
      - TS_AUTH_KEY
      - TS_EXTRA_ARGS
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - type: volume
        source: tailscale
        target: /var/lib/tailscale
      - type: volume
        source: tailscale_sock
        target: /tmp
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - nextcloud-aio
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line cannot change.
  caddy_certs:
    name: caddy_certs
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  tailscale:
    name: tailscale
  tailscale_sock:
    name: tailscale_sock
networks:
  nextcloud-aio:
    name: nextcloud-aio
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1" # Harden AIO
